#!/usr/bin/python3

from gccf import format_gcc_output

command = 'g++ -Wall -Wextra -fdiagnostics-format=sarif-stderr test2.cpp'
format_gcc_output (command)

print ("----------------")

command = 'gcc -Wall -Wextra -fdiagnostics-format=sarif-stderr test1.c'
format_gcc_output (command)

